"""Added this to video a task model ForeignKey('tasks.task_id')

Revision ID: 1cb09f5f5ff0
Revises: 672ca4fc0cd9
Create Date: 2026-08-12 13:00:19.238090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb09f5f5ff0'
down_revision: Union[str, Sequence[str], None] = '672ca4fc0cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'videotask', 'tasks', ['task_id'], ['task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videotask', type_='foreignkey')
    # ### end Alembic commands ###
