"""Added this column to it video_task_id

Revision ID: 6549c0138fa8
Revises: 1cb09f5f5ff0
Create Date: 2026-08-12 21:30:59.823049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6549c0138fa8'
down_revision: Union[str, Sequence[str], None] = '1cb09f5f5ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videotask', sa.Column('video_task_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_videotask_video_task_id'), 'videotask', ['video_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videotask_video_task_id'), table_name='videotask')
    op.drop_column('videotask', 'video_task_id')
    # ### end Alembic commands ###
