"""Add price_of_product and url_of_product column to Task table

Revision ID: d3042cb4872b
Revises: b20569c1fee3
Create Date: 2026-08-14 14:58:43.761409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3042cb4872b'
down_revision: Union[str, Sequence[str], None] = 'b20569c1fee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('price_of_product', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('url_of_product', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'url_of_product')
    op.drop_column('tasks', 'price_of_product')
    # ### end Alembic commands ###
